### ISSUE TITLE
USER STORY:Read/ apply/ save a job

### ISSUE THREAD

**Issue by Xh3ni** [Xh3ni/LyhnidasYourJobCoach#13]
As a **candidate** I can **read/ apply/ save a job** so that **I can ensure maximum engagement in my profile**

**Acceptance Criteria**
Logged-in candidates can:

- [x] Search for a job
- [x] Appy for a job
- [x] Save a job
- [x] Can see the current status of the application: whether its accepted, pending or rejected
