### ISSUE TITLE
USER STORY: The Ability to read/ appy/ save for a job

### ISSUE THREAD

**Issue by Xh3ni** [Xh3ni/LyhnidasYourJobCoach#14]
As a **candidate** I can **be able to read/ apply/ save a job** so that **I can alter how I would like my job application to look to allow for maximum engagement**

**Acceptance Criteria**

- [x] If logged in, user can apply for a job or more
- [x] If logged in, user can save a job or more
- [x] If logged in, user can see whether the application is accepted, pending or rejected
