### ISSUE TITLE
USER STORY: The Ability to read/ edit/ delete a job post & Candidates as a recruiter

### ISSUE THREAD

**Issue by Xh3ni** [Xh3ni/LyhnidasYourJobCoach#20]
As a **Recruiter** I can **be able to Read/ edit/ delete a job post & Candidates** so that **I can ensure the perfect candidate for the job position**

**Acceptance Criteria**

- [x] If logged in, recruiter can add a job or more
- [x] If logged in, recruiter can edit a job
- [x] If logged in, recruiter can delete a job
- [x] If logged in, recruiter can see the current status of the job post, like how many have applied
- [x] If logged in, recruiter can see the applicants list and then select or reject them based on their profile and resume
