### ISSUE TITLE
USER STORY: Edit/Update/Delete a job post

### ISSUE THREAD

**Issue by Xh3ni** [Xh3ni/LyhnidasYourJobCoach#3]
As an **admin** I can **add/edit/update/delete a job post** so that **maintain the site and remove any inappropriate contents**

Acceptance Criteria
When content on the website is published, admin should be able to:

- [x] Add any job posts
- [x] Edit any job posts from site users and themselves
- [x] Update any job posts from site users and themselves
- [x] Delete any job posts from site users and themselves
