### ISSUE TITLE
USER STORY: Have an user-friendly and functional website

### ISSUE THREAD

**Issue by Xh3ni** [Xh3ni/LyhnidasYourJobCoach#5]
As an **admin** I want**an user-friendly website and have no bugs, ** so that **I can ensure an enjoyable browsing experience for all users**

Acceptance Criteria

- [ ]  E2E testing performed on all functionalities to ensure site is working as intended
- [ ] Docmentation of testing and outcomes
- [ ] Bugs highlighted and fixed or added to ReadMe.md file
