### ISSUE TITLE
USER STORY: Easy access to the website as a job seeker

### ISSUE THREAD

**Issue by Xh3ni** [Xh3ni/LyhnidasYourJobCoach#7]
As a **first time user as a candidate** I want to  **be able to know what is expected of me on the home page** so that **I can easily navigate and find information**

Acceptance Criteria

- [x] Navigation bar
- [x] Easy to identify website purpose
- [x] Text is easy to read
- [x] It's easy to find where to sign-up
- [x] Job list is easy to find
